-- create_table.sql (Dummy)
CREATE TABLE demo_inbound (
  txn_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  acct_no     VARCHAR2(30),
  txn_amount  NUMBER(12,2),
  txn_date    DATE,
  status      VARCHAR2(20),
  created_ts  DATE DEFAULT SYSDATE
);

CREATE TABLE demo_staging AS SELECT * FROM demo_inbound WHERE 1=0;
CREATE TABLE demo_target AS SELECT * FROM demo_inbound WHERE 1=0;
